# training data for semantic Similarity to Fine Tune the Model.

from sentence_transformers import InputExample

train_examples = [
    # 1. College Overview
    InputExample(texts=["What is the Vision of the College?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Describe the college in brief.", "Tell me about the College."], label=1.0),
    InputExample(texts=["When was the college established?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the motto of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you provide a brief overview of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["How would you describe the college in a few sentences?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Summarize the main features of the college.", "Tell me about the College."], label=1.0),
    InputExample(texts=["What are the key highlights of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Give a short description of the college.", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the college like in general?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Share a quick overview of the college.", "Tell me about the College."], label=1.0),
    InputExample(texts=["What are the most notable aspects of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Could you explain the college in brief?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the establishment year of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["When did the college come into existence?", "Tell me about the College."], label=1.0),
    InputExample(texts=["In which year was the college founded?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you tell me the founding year of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What year was the college set up?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the college's official motto?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you share the motto of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What phrase represents the college's values or mission?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the guiding principle of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What slogan or motto does the college follow?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Give an overview of this institution.", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you provide a brief history of this institution?", "Tell me about the College."], label=1.0),
    InputExample(texts=["How did this institution come into existence?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What are the origins of this institution?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Could you share the background story of this institution?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the founding history of this institution?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Does the college outline a specific mission statement?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the mission statement of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Is there an official mission statement for the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Does the college have a defined purpose or mission?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What guiding mission does the college follow?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you tell me the location of the college and describe its campus?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Where is the college situated, and how is the campus environment?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the college's location, and what are the campus facilities like?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Where can I find the college, and what does the campus look like?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the address of the college, and how would you describe its campus?", "Tell me about the College."], label=1.0),

    
    # 2. Courses Offered
    InputExample(texts=["What programs I can join after 12th?", "What courses are offered?"], label=1.0),
    InputExample(texts=["Do you offer undergraduate courses?", "What types of degrees can I pursue here?"], label=1.0),
    InputExample(texts=["Are there any diploma programs?", "Can I pursue certificate courses here?"], label=1.0),
    InputExample(texts=["Are part-time courses available?", "Do you offer evening or weekend classes?"], label=1.0),

    # 3. Admissions
    InputExample(texts=["How can I apply?", "What is the admission process?"], label=1.0),
    InputExample(texts=["Is there an entrance exam?", "What are the eligibility criteria for admission?"], label=1.0),
    InputExample(texts=["What documents are required for admission?", "Can I apply online for admission?"], label=1.0),
    InputExample(texts=["When does the admission process start?", "What are the key deadlines for applying?"], label=1.0),

    # 4. Campus Facility
    InputExample(texts=["Does this college have a library on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Do you provide hostel facilities?", "What infrastructure does the campus have?"], label=1.0),
    InputExample(texts=["Is there a cafeteria on campus?", "Are there any sports facilities available?"], label=1.0),
    InputExample(texts=["Does the college have Wi-Fi facilities?", "Are classrooms equipped with smart boards?"], label=1.0),

    # 5. Faculty
    InputExample(texts=["Who is the principal of the college?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Are the professors qualified?", "Who are some notable faculty members?"], label=1.0),
    InputExample(texts=["Do faculty members have industry experience?", "Are professors approachable for students?"], label=1.0),
    InputExample(texts=["How often do faculty members hold office hours?", "Is mentoring provided by faculty?"], label=1.0),

    # 6. Departments
    InputExample(texts=["How many Departments do you have?", "Does this college have the Engineering Department?"], label=1.0),
    InputExample(texts=["Is there a Computer Science department?", "What academic divisions are offered?"], label=1.0),
    InputExample(texts=["Do you have a Department of Humanities?", "Does the college offer medical-related departments?"], label=1.0),
    InputExample(texts=["How many departments does the college have?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the different academic departments?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Are there specialized departments for emerging fields?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many students are enrolled in each department?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Are there specialized departments for emerging fields?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=[" What are the departmental strengths and specializations?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Are there any departments with industry collaborations?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments offer undergraduate programs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=[" What is the faculty-student ratio in each department?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments have research centers or institutes?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=[" What are the departmental initiatives for entrepreneurship?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=[" How many departments offer online or distance learning programs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the admission requirements for each department?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental ranking and recognition?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments offer minors or certificate programs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Are there any departments with study abroad programs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments have student organizations or clubs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments offer internship or co-op programs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Are there any departments with industry-sponsored projects?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments have advisory boards?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Are there any departments with industry partnerships for research?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=[" What are the departmental initiatives for sustainability?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments offer courses on sustainability?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=[" What are the departmental initiatives for social responsibility?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=[" How many departments have community service projects?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=[" Are there any departments with industry-sponsored community projects?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=[" What are the departmental initiatives for innovation and entrepreneurship?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments offer courses on innovation and entrepreneurship?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental initiatives for industry collaboration?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments have research collaborations with industry?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Are there any departments with industry-sponsored research projects", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental initiatives for student innovation?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments offer innovation competitions or challenges?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental initiatives for faculty innovation?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How many departments offer innovation training or workshops?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments collaborate with each other?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the most popular departments among students?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student research?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments engage with industry partners?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support diversity and inclusion?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments evaluate faculty performance?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What role do departments play in shaping the college's strategic plan?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student career development?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you describe the departmental decision-making process?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments prioritize research projects?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you name some departmental research centers or institutes?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student entrepreneurship?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you describe the departmental process for curriculum development?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments evaluate program effectiveness?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental goals and objectives?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental policies on academic integrity?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you name some departmental study abroad programs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student innovation?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental policies on faculty mentoring?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you describe the departmental role in college governance?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student organizations?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you name some departmental community engagement projects?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you describe the departmental process for faculty recruitment??", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student internship programs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you name some departmental industry partnerships?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental goals for student retention?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental policies on student complaints?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you name some departmental research grants?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental goals for community outreach?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student volunteer programs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you describe the departmental role in college internationalization?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student study abroad programs?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental initiatives for international research collaborations?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student international internships?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you name some departmental global research projects?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental goals for student success?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student career counseling?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["How do departments support student academic advising?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["Can you name some departmental student success initiatives?", "Is there a business school or management department?"], label=1.0),
    InputExample(texts=["What are the departmental policies on student retention strategies?", "Is there a business school or management department?"], label=1.0),

    # 7. Fees Structure
    InputExample(texts=["What is the fee Structure?", "How much does a program cost?"], label=1.0),
    InputExample(texts=["Are there any scholarships available?", "Can you tell me about tuition fees?"], label=1.0),
    InputExample(texts=["Is there a difference in fees for international students?", "Are there installment options for fee payment?"], label=1.0),
    InputExample(texts=["Do you offer financial aid?", "What are the additional costs like hostel or library fees?"], label=1.0),

    # 8. Placement and Career Opportunities
    InputExample(texts=["What are the placement opportunities?", "Do students get campus placements?"], label=1.0),
    InputExample(texts=["What is the highest package offered?", "Do you have a career placement cell?"], label=1.0),
    InputExample(texts=["What companies visit for recruitment?", "What is the average placement percentage?"], label=1.0),
    InputExample(texts=["Are internships provided?", "Do you help students find internships?"], label=1.0),

    # 9. Alumni Network
    InputExample(texts=["Does the college have a strong alumni network?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can alumni help students with placements?", "Is there an alumni association?"], label=1.0),
    InputExample(texts=["Do alumni frequently visit the campus?", "Are alumni involved in mentorship programs?"], label=1.0),
    InputExample(texts=["How can students connect with alumni?", "How does the alumni network support the institution?"], label=1.0),
    InputExample(texts=["Does the college have an alumni portal?", "How does the alumni network support the institution?"], label=1.0),
    InputExample(texts=["What are the benefits of joining the alumni association?", "How does the alumni network support the institution?"], label=1.0),
    InputExample(texts=["How do alumni contribute to the college?", "How does the alumni network support the institution?"], label=1.0),
    InputExample(texts=["What are the success stories of alumni?", "How does the alumni network support the institution?"], label=1.0),
    InputExample(texts=["What percentage of Baba Farid Group of Institutions' alumni are placed in top companies within six months of graduation??", "How does the alumni network support the institution?"], label=1.0),
    InputExample(texts=[" What is the average package offered to alumni of Baba Farid Group of Institutions?", "How does the alumni network support the institution?"], label=1.0),
    InputExample(texts=[" What are the most common career paths or job titles among Baba Farid Group of Institutions' alumni within the first five years of graduation??", "How does the alumni network support the institution?"], label=1.0),
    InputExample(texts=["Which branches of engineering (e.g., CSE, ECE, ME) have the highest alumni placement rates?", "How does the alumni network support the institution?"], label=1.0),

    # 10. Events and Activities
    InputExample(texts=["What kind of extracurricular activities are available?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Is there a cultural festival?", "Are sports facilities available for students?"], label=1.0),
    InputExample(texts=["Do you have student clubs or societies?", "Are there opportunities for community service?"], label=1.0),
    InputExample(texts=[" Does the campus host technology exhibitions or fairs? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there electronics or maker fairs for students? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  What kinds of events are held to promote student wellness? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college host hackathons, competitions, or project showcases? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there workshops or seminars for skill-building outside academics?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there awareness events on mental health or wellness? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["Are there events focused on innovation or entrepreneurship?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there book fairs or literary events on campus?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college host annual cultural festivals? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there music or dance performances by students?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["Are there celebrations for national or international festivals?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there fashion shows or style-based competitions? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Is there a college band or choir that performs regularly?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there open-mic nights or poetry slams?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["Are inter-departmental competitions a regular occurrence?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there any cultural or art-focused events held regularly?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the campus host drama or theater performances? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there culinary or food festivals held?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Do students organize photography or art exhibitions?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there annual sports meets or tournaments? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Does the college participate in inter-collegiate sports events?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are marathons or fitness challenges held on campus?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there recreational games or matches for non-athletes?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college organize yoga or wellness workshops? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there outdoor adventure or trekking events?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there workshops on self-defense or martial arts?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are blood donation camps held on campus?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Does the college host charity drives or fundraisers?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there clean-up or environmental awareness drives? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there initiatives to support underprivileged communities?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there health check-up camps for students and staff?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there tree plantation or sustainability events? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the campus host technology exhibitions or fairs? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there workshops on AI, ML, or data science? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there electronics or maker fairs for students?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there simulation or virtual reality-related events? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are blockchain or cryptocurrency seminars conducted?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Does the college host guest lectures by industry experts?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there career guidance events or sessions? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Is there an annual research paper presentation event? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["Are mock interviews or resume-building workshops conducted?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there opportunities to participate in debates or elocution contests?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Does the college celebrate major festivals?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there poetry or creative writing events?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there fashion shows or style-related contests? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["Are there self-defense or martial arts workshops?   ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the campus host cricket, football, or basketball leagues?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there opportunities for swimming or track events?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college offer cycling or marathon events?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there friendly matches between students and faculty? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college host technology-focused fests or expos?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there robotics or drone competitions?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are AI and ML-related workshops conducted?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college organize electronics or engineering challenges? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there app development or software design contests?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["Is there a dedicated technology day or event?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there 3D printing or VR-related activities?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are blood donation or health check-up camps held? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college organize environmental clean-up drives?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are tree plantation or sustainability events conducted?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there mental health awareness workshops?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["Are there volunteering opportunities in nearby communities?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the campus celebrate World Environment Day or Earth Day? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are cultural exchange programs or international days observed? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there events for alumni interaction and networking?  ", " what kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college hold awareness programs on social issues?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there opportunities for publishing research papers?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[ "Are coding and programming boot camps organized?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Is there a debate or public speaking club?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Are there music or dance clubs?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there theater and drama workshops?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there regular art and craft workshops?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are photography and videography activities conducted? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the institution celebrate festivals like Diwali or Holi? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college host fashion shows?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  Does the college offer indoor sports facilities?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there adventure sports or trekking activities?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["Are there swimming or aquatic events? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college have an NSS (National Service Scheme) unit? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there hackathons or coding competitions? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college provide startup mentorship?  ?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are motivational speaker sessions organized?", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the institution celebrate UN-recognized days like World Environment Day?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there trips to cultural heritage sites?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" What are the major annual events hosted on campus?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" When is the next cultural fest?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" How often does the college organize workshops?   ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there any inter-college competitions? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Is there an annual cultural festival?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there opportunities to showcase musical talents?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Does the college invite external artists for events? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there photography or art exhibitions?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" What workshops are planned for this semester?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there any upcoming hackathons?   ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there industry experts invited for guest talks? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there inter-departmental sports competitions? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are photography or film-making contests held? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are national holidays celebrated?  ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["Are religious events organized for various communities? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=["  What community service events are organized? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there coding marathons or hackathons? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are 3D printing workshops conducted? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are there movie nights organized on campus? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Is there a campus-wide talent hunt? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are special transport services provided for late events? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" What equipment is available for organizing events? ", "What kind of extracurricular activities are available?"], label=1.0),
    InputExample(texts=[" Are special transport services provided for late events? ", "What kind of extracurricular activities are available?"], label=1.0),

    # 11. Research Opportunities
    InputExample(texts=["Does the college support research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I participate in research projects?", "Is there funding available for research?"], label=1.0),
    InputExample(texts=["Are research internships offered?", "Do faculty members collaborate with students on research?"], label=1.0),
    InputExample(texts=["Does the college publish a research journal?", "Is there a research center for PhD students?"], label=1.0),

    # 12. International Collaboration
    InputExample(texts=["Does the college have international partnerships?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are there opportunities to study abroad?", "Does the college offer global exposure?"], label=1.0),
    InputExample(texts=["Are foreign language courses available?", "Does the college have collaboration with global universities?"], label=1.0),
    InputExample(texts=["Are international internships facilitated?", "What are the options for cross-cultural learning?"], label=1.0),

    # 13. Online Learning and Resources
    InputExample(texts=["Are online courses available?", "Can students access digital libraries?"], label=1.0),
    InputExample(texts=["What e-learning tools are provided?", "Does the college use online learning platforms?"], label=1.0),
    InputExample(texts=["Is there access to virtual labs?", "Are recorded lectures provided?"], label=1.0),
    InputExample(texts=["Are students taught using online simulations?", "Do you offer online certification programs?"], label=1.0)
]

def get_training_data():
    """Return the training examples."""
    return train_examples

if __name__ == "__main__":
    print("This module contains intent training data for fine-tuning.")