# training data for semantic Similarity to Fine Tune the Model.

from sentence_transformers import InputExample

train_examples = [
    # 1. College Overview
    InputExample(texts=["What is the Vision of the College?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Describe the college in brief.", "Give an overview of this institution."], label=1.0),
    InputExample(texts=["When was the college established?", "What is the history of this institution?"], label=1.0),
    InputExample(texts=["What is the motto of the college?", "Does the college have a mission statement?"], label=1.0),
    InputExample(texts=["Can you tell me about the college’s history and when it was established?", "Tell me about the College."], label=1.0),

    # college overview and course offered label 0.0

    # 2. Courses Offered
    InputExample(texts=["What programs I can join after 12th?", "What courses are offered?"], label=1.0),
    InputExample(texts=["What programs I can join after 12th?", "What courses are offered?"], label=1.0),
    InputExample(texts=["Do you offer undergraduate courses?", "What types of degrees can I pursue here?"], label=1.0),
    InputExample(texts=["Are there any diploma programs?", "Can I pursue certificate courses here?"], label=1.0),
    InputExample(texts=["What undergraduate programs does BFGI offer after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there any diploma courses available at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Which courses at BFGI are most popular among students after 12th? ", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer science-based degree programs? ", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there any commerce-related courses at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What are the arts programs available at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there any professional degree programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What technical courses can I pursue at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer management courses for 12th pass students? ", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What are the engineering courses offered at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI have B.Sc. programs for science students?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a B.Sc. in Agriculture at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there biotechnology programs available at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer a B.Sc. in Computer Science?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are medical-related courses available at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What are the opportunities for studying physics or chemistry at BFGI?  ", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer environmental science programs?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there any forensic science courses at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I enroll in a B.Sc. (Hons.) program at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=[" What are the options for commerce students at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer B.Com (Hons.) programs?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a degree in finance at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What accounting courses are available at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there banking and insurance courses offered at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What business studies programs does BFGI offer?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What business studies programs are offered?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Is there a BBA (Bachelor of Business Administration) program at BFGI?  ", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI have entrepreneurship-focused programs?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I study economics at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there short-term diploma programs in commerce at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What humanities courses does BFGI offer after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a BA in English at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a BA in Sociology at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a BA in History at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a BA in Punjabi at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer psychology programs?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a BA in Psychology at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there journalism and mass communication courses at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What history and political science programs are available at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I study sociology or anthropology at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI have programs in fine arts or design?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there performing arts programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=[" Can I pursue language studies (e.g., Punjabi, Hindi) at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there any diploma programs in social sciences at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer a B.Tech in Computer Science?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I study Artificial Intelligence (AI) at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there programs in data science or machine learning at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What software development courses are available at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI have cybersecurity-related programs?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there gaming or animation courses at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a diploma in IT at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What are the options for app and web development studies at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer BCA (Bachelor of Computer Applications)?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there integrated B.Tech + M.Tech programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there nursing programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer pharmacy-related courses?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a degree in physiotherapy at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=[" Are there medical lab technology programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer paramedical courses?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What are the options for studying healthcare administration at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I study public health at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI have programs in nutrition and dietetics?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there radiology courses offered at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What life sciences programs are available at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer an integrated MBA program?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=[" Can I pursue event management at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there hospitality management courses at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What international business programs are available at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I study supply chain management at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer programs in human resource management?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=[" Are there marketing or advertising courses at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I enroll in business analytics programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI have leadership and strategy courses?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there retail management programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What agriculture courses are available at BFGI after 12th?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I study agribusiness management at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer programs in organic farming?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there programs focused on rural development at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue soil science studies at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI have courses in horticulture?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there agricultural engineering programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What livestock management courses are offered by BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I study agricultural economics at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there diploma courses in modern farming techniques at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer graphic design programs?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I study fashion design at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there interior design courses at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=[" What programs are available for photography enthusiasts at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer courses in animation and VFX?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I enroll in industrial design programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there web design and UX/UI programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI have courses in textile design?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What are the opportunities for studying jewelry design at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there visual arts programs offered at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer environmental sustainability programs?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue sports management at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there courses in renewable energy at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer degrees in robotics or automation? ", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What are the options for studying blockchain technology at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue aviation management at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there programs in forensic accounting at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI have international studies programs?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=[" Can I study artificial intelligence as part of an engineering course at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What are the career-oriented certification programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What career-oriented certification programs does BFGI offer?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there any short-term certification programs for skill development at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer certifications in digital marketing?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a certificate in data science at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there AI and machine learning certification programs at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI provide certifications in entrepreneurship?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What IT-related certification courses are available at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I enroll in a certification program for financial accounting at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there certifications in programming languages like Python or Java at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=[" Does BFGI offer certifications in ethical hacking or cybersecurity?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What healthcare-related certification programs does BFGI provide?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there certifications in agriculture and modern farming techniques at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I pursue a graphic design or web design certification at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What certifications are available in business analytics or project management at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there certification programs in supply chain management at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Does BFGI offer a certificate course in leadership and soft skills?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Are there specialized certifications for MBA students at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["Can I earn a certification in sports management at BFGI?", "Do you offer evening or weekend classes?"], label=1.0),
    InputExample(texts=["What creative field certifications, such as animation or video editing, does BFGI provide?", "Do you offer evening or weekend classes?"], label=1.0),
   
    # 3. Admissions
    InputExample(texts=["How can I apply?", "What is the admission process?"], label=1.0),
    InputExample(texts=["Is there an entrance exam?", "What are the eligibility criteria for admission?"], label=1.0),
    InputExample(texts=["What documents are required for admission?", "Can I apply online for admission?"], label=1.0),
    InputExample(texts=["What are the application deadlines?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Is there an online application process?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What documents are required for the application?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I apply to multiple programs simultaneously?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Is there an entrance exam required?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are interviews part of the admission process?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["When does the admission process start?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the minimum percentage/grade required for eligibility?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there specific subjects required for eligibility?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are extracurricular activities considered during the admission process?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are letters of recommendation mandatory?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there any specific requirements for international students?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I submit additional materials like portfolios or certificates?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are my past academic achievements weighted during selection?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What undergraduate programs are offered?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there dual-degree programs available?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I change my major after admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the admission process for international students?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there additional documents required for international students?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Does the college assist with visa applications?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are English proficiency tests like IELTS/TOEFL mandatory?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there orientation programs for international students?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the attendance policy?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the grading system used?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I defer my admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=[" Is the admission process competitive?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I track the status of my application?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I reach the admissions office for queries?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What are the steps to apply for admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Where can I find the application form?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["When does the application process begin?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the deadline for submitting the application?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I know if I am eligible to apply?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I apply online or only in person?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I submit the required documents?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What documents are needed for admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I edit my application after submitting it?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I track the status of my application?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Is there an entrance exam for admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I register for the entrance exam?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["When is the entrance exam conducted?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the syllabus for the entrance exam?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How many times can I attempt the entrance exam?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the passing score for the entrance exam?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I apply without taking the entrance exam?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Is there a mock test available for the entrance exam?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I prepare for the entrance exam?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Is there a fee for the entrance exam?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there any additional fees during the admission process?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What are the minimum marks required for admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there specific eligibility criteria for certain programs?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can international students apply?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are working professionals eligible for admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I apply if I am waiting for my final exam results?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=[" What documents are required for verification?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I submit soft copies of my documents?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I certify my documents?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What happens if I miss the document verification date?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=[" Are there any additional fees during the admission process?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there specific eligibility criteria for certain programs?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I apply for multiple programs at once?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I know which programs I am eligible for?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I switch my program after being admitted?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the process for international students?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Do I need a student visa to apply?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I apply without an English proficiency test?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are interviews a part of the admission process?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How will I be notified if I am admitted?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["When will the admission results be announced?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What should I do if my application is rejected?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Is there a waitlist for admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I confirm my admission after being selected?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What are the important dates for admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the last date to submit documents?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the policy for deferred admissions?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Is there a minimum attendance policy after admission?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I transfer my admission to another college?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What is the process for admission through sports quota?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there reserved seats for certain categories?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I apply under the reserved category?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there special provisions for differently-abled students?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Is there a separate process for NRI applicants?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can I defer my admission to the next semester?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Who can I contact for admission-related questions?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Can parents accompany students during the admission process?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Is there a helpline number for admission queries?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I stay updated about admission announcements?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I stay informed about new admission updates?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there websites for real-time admission announcements? ", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Which mobile apps notify about admission updates?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I get email updates for admissions?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there forums for admission-related discussions?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I track international university admission updates? ", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I stay updated on entrance exam dates?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I keep track of application openings? ", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there Telegram groups for admission news?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Where do I find MBA program admission updates?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I connect with admission counselors online?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["What’s the best way to find walk-in admission updates?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Are there specific admission groups on LinkedIn?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I get notifications for postgraduate program admissions?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How do I keep track of results for entrance exams?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["Where can I find details about admission fairs?", "What are the key deadlines for applying?"], label=1.0),
    InputExample(texts=["How can I stay updated about changes in admission criteria?", "What are the key deadlines for applying?"], label=1.0),
    
    # 4. Campus Facility
    InputExample(texts=["Does this college have a library on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Do you provide hostel facilities?", "What infrastructure does the campus have?"], label=1.0),
    InputExample(texts=["Is there a cafeteria on campus?", "Are there any sports facilities available?"], label=1.0),
    InputExample(texts=["Does the college have Wi-Fi facilities?", "Are classrooms equipped with smart boards?"], label=1.0),
    InputExample(texts=["What types of study spaces are available for students on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there specialized libraries for different subjects or disciplines?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a digital or e-library for online resources and research?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college provide access to academic journals or research databases?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there quiet study rooms or soundproof areas for focused work?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students reserve library spaces for group study sessions?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the library offer printing or scanning services?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["How long can students borrow books or other materials from the library?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any extended library hours during exams or busy periods?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have a gym or fitness center for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any indoor or outdoor sports facilities available on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["What kind of recreational sports equipment is available for student use?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a swimming pool or aquatic center on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there spaces for group fitness classes or personal training?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college offer any athletic programs or teams for students to join?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there tennis courts or basketball courts available for student use?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students use the gym for free or is there a membership fee?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a running track or other outdoor exercise spaces on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there fitness-related clubs or activities organized by the college?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a computer lab available for students on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college provide access to computers for student use?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any dedicated spaces with computers for academic work?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any labs with specialized software for students to use?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a public computer area for students who need to complete assignments?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there computers available for students to use during library hours?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have any technology resources like computer labs or digital workstations?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any computer labs with printing services on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["How many computer labs are available for students to access on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students use computers in the lab for both personal and academic purposes?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have a designated student lounge or hangout space?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any common areas where students can relax between classes?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a place on campus where students can unwind or socialize?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any lounges or recreational spaces for students to take a break?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students access any casual spaces for group discussions or relaxation?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college provide areas for students to relax and recharge?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there comfortable seating areas on campus for students to study or socialize?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a coffee shop or café where students can relax and meet friends?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any spaces with sofas or lounges where students can rest during the day?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there an outdoor area on campus where students can hang out and relax?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is Wi-Fi available in all the buildings on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students connect to the internet in every classroom or facility?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any areas on campus where Wi-Fi is not accessible?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college offer free Wi-Fi throughout the entire campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students use Wi-Fi in libraries, classrooms, and other campus locations?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is campus-wide Wi-Fi available in all student common areas?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any restrictions or limits on Wi-Fi usage for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students access Wi-Fi in the dorms as well as academic buildings?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is the campus Wi-Fi fast and reliable for academic work?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college provide any support if students have trouble connecting to Wi-Fi?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["What dining facilities are available for students on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have any cafeterias or food courts?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any restaurants or cafés on campus where students can eat?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["What types of meals or snacks are served in the on-campus dining areas?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a variety of food options available for students with dietary restrictions?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students get breakfast, lunch, and dinner on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any vegan or vegetarian-friendly food options on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the campus have a food delivery service or mobile ordering app?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["How affordable are the dining options on campus for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any specialty food vendors or food trucks on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a medical center or health services available to students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have a health center for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any medical services or clinics available on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a doctor or nurse available to students on campus for health concerns?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["What kind of health services are offered to students at the college?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students access mental health support or counseling services on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any emergency medical services or first aid stations on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the campus health center provide routine check-ups or vaccinations?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a pharmacy or dispensary on campus for students to use?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students schedule appointments for medical consultations at the college?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any health-related workshops or resources available to students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any career services available to students on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college offer job placement assistance or internships for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students get help with resume writing or interview preparation?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a career counseling service for students to explore career options??", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have any partnerships with companies or organizations for student internships?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there workshops or events focused on career development or job search strategies?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students access networking opportunities or job fairs through the college?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the career center provide one-on-one counseling for students seeking jobs?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there resources available for students to explore different career paths?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["How does the college support students in securing employment after graduation?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college offer any student organizations or clubs to join?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any extracurricular activities available for students to participate in?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students get involved in social, cultural, or academic clubs on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any student-run clubs or societies for different interests?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["How can students find out about clubs or extracurricular events happening on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there volunteer opportunities or community service clubs for students to join?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any sports teams or recreational leagues for students to participate in?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have any clubs focused on leadership, entrepreneurship, or professional development?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["How do students typically get to campus? Are there public transportation options?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college offer shuttle services for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any campus bus routes or transit passes available for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["is parking available on campus for students with cars?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any bike racks or bike-sharing programs available at the college?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college provide transportation for students to nearby areas or events?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["How far is the campus from the nearest public transit station?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a carpool program or ride-sharing options for students??", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students use ride-hailing services like Uber or Lyft to get to campus easily?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any discounted transportation options for students, such as metro passes?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college provide on-campus housing for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any dormitories or student residences available on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students live in campus-hosted apartments or shared accommodations?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["What types of housing options are available for students at the college?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any off-campus housing resources or recommendations for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a waitlist for on-campus accommodation, and how can students apply?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Do students have the option to choose between single or shared rooms in the dorms?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any special housing arrangements for first-year or international students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any green spaces on campus with picnic tables or benches?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the campus have any outdoor spots with Wi-Fi for students to work in?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any outdoor areas on campus where students can hang out or study?", "What are the facilities available here?"], label=1.0),
    

    # 5. Faculty
    InputExample(texts=["Who is the principal of the college?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Are the professors qualified?", "Who are some notable faculty members?"], label=1.0),
    InputExample(texts=["Do faculty members have industry experience?", "Are professors approachable for students?"], label=1.0),
    InputExample(texts=["How often do faculty members hold office hours?", "Is mentoring provided by faculty?"], label=1.0),

    # 6. Departments
    InputExample(texts=["How many Departments do you have?", "Does this college have the Engineering Department?"], label=1.0),
    InputExample(texts=["Is there a Computer Science department?", "What academic divisions are offered?"], label=1.0),
    InputExample(texts=["Do you have a Department of Humanities?", "Does the college offer medical-related departments?"], label=1.0),
    InputExample(texts=["Are there specialized departments for emerging fields?", "Is there a business school or management department?"], label=1.0),

    # 7. Fees Structure
    InputExample(texts=["What is the fee Structure?", "How much does a program cost?"], label=1.0),
    InputExample(texts=["Are there any scholarships available?", "Can you tell me about tuition fees?"], label=1.0),
    InputExample(texts=["Is there a difference in fees for international students?", "Are there installment options for fee payment?"], label=1.0),
    InputExample(texts=["Do you offer financial aid?", "What are the additional costs like hostel or library fees?"], label=1.0),

    # 8. Placement and Career Opportunities
    InputExample(texts=["What are the placement opportunities?", "Do students get campus placements?"], label=1.0),
    InputExample(texts=["What is the highest package offered?", "Do you have a career placement cell?"], label=1.0),
    InputExample(texts=["What companies visit for recruitment?", "What is the average placement percentage?"], label=1.0),
    InputExample(texts=["Are internships provided?", "Do you help students find internships?"], label=1.0),

    # 9. Alumni Network
    InputExample(texts=["Does the college have a strong alumni network?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can alumni help students with placements?", "Is there an alumni association?"], label=1.0),
    InputExample(texts=["Do alumni frequently visit the campus?", "Are alumni involved in mentorship programs?"], label=1.0),
    InputExample(texts=["Does the college have an alumni portal?", "How does the alumni network support the institution?"], label=1.0),
    InputExample(texts=["Who are some of the top achievers who graduated from this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you list any successful alumni from this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["What alumni from this school have reached great heights in their careers?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the most accomplished former students of this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which alumni from this college have made a significant impact in their fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some of the most influential graduates from this university?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about any alumni who have become highly successfu?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["What are some examples of alumni who have achieved remarkable success?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some former students who have gone on to excel professionally?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["What graduates from this college are known for their extraordinary achievements?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some well-known people who went to this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about any famous graduates from here?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any notable figures who earned their degree from this school?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some celebrities or public figures that studied here?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which well-known people are alumni of this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you share a list of famous individuals who graduated from this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some prominent graduates from this university?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any renowned people who have walked through the halls of this school?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which famous personalities are associated with this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you name any influential people who are alumni of this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some influential people who have studied at this school?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about some famous individuals who have been students here?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which well-known figures have attended this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some prominent people who graduated from this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["What notable alumni have passed through this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you share any stories about famous people who were once students here?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the most distinguished individuals to have studied at this school?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which notable people have been part of the student body here?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you name any high-profile individuals who attended this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some prominent graduates who have had a major influence in their respective fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you name any alumni who have achieved great success in their careers?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which former students have left a lasting mark on their industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some well-known alumni that have made a big impact in the professional world?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any graduates who have become leaders or innovators in their fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["What alumni are recognized for their significant contributions to their professions?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some of the most influential alumni in various industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about any former students who’ve had a lasting effect on their industry?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some of the most successful alumni and how have they impacted their industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some of the most famous alumni from this university?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some influential people who studied at this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which notable individuals have graduated from this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you list any well-known graduates from this university?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the most high-profile alumni of this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["What are some of the most recognizable names to have attended this university?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the standout alumni from this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you name any famous former students of this university?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which notable people have received their degrees from this school?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some of the top names that have come out of this university?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which alumni from this college have made significant contributions to their industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about some of the successful graduates of this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some prominent alumni from this college who have achieved leadership in their careers?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which former students of this college are considered influential in their professions?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the standout alumni of this college known for their professional success?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any notable alumni from this college who have become leaders in their respective fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which graduates of this college are recognized as leaders in their industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some of the most accomplished alumni from this college in terms of professional impact?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you name some alumni from this college who have excelled in their careers?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the most distinguished former students of this college in their professions?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Have any alumni from this college received notable awards or recognitions?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any graduates from this college who have been honored with prestigious accolades?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you share any examples of alumni who have earned significant awards or honors?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which alumni from this college have received esteemed recognitions or prizes?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Have any former students from this college won major awards or honors in their fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any alumni who have been acknowledged with high-profile awards or distinctions?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some notable graduates of this college who have received prestigious honors?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about any alumni who have been celebrated with prestigious awards?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which former students from this college have received top honors or accolades in their careers?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Do any alumni from this college have a history of winning major awards or recognitions?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which alumni from this college are known for breaking new ground in their professions?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the pioneers from this college who have led the way in their industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about any alumni who have been innovators in their fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the alumni from this college that have led transformative changes in their industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which former students from this college are recognized for being industry leaders or trendsetters?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any alumni who have revolutionized their fields or created new paths in their professions?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the alumni who are known for charting new territory in their careers?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which graduates from this college are considered forward-thinking trailblazers in their areas of expertise?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you share any stories of alumni who have helped shape the future of their industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the groundbreakers among the alumni of this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which alumni have been at the forefront of change or innovation in their fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any graduates from this college who have led pioneering efforts in their professional fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the alumni who have introduced groundbreaking ideas or practices in their industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which alumni are regarded as visionaries or trailblazers in their respective careers?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about any alumni who have been pioneers in creating new opportunities or industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any well-known political figures or business leaders who are alumni of this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Have any prominent politicians or business executives graduated from here?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which famous politicians or top business leaders are former students of this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you name any alumni from this college who have risen to political or business leadership?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some influential politicians or business figures who graduated from this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are any notable political leaders or corporate executives alumni of this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Do any prominent business leaders or politicians have a degree from this school?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about any alumni who have gone on to become significant political or business figures?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which well-known leaders in politics or business have roots at this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any distinguished business professionals or politicians who attended this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the alumni from this college who have made their mark in politics or business?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Have any notable politicians or corporate leaders come from this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you share the names of alumni who have gone on to influential careers in politics or business?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any famous figures in business or government who earned their degree from here?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which political leaders or business moguls are graduates of this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Have any alumni from this college achieved fame in the fields of politics or business?", "Who are some notable alumni?"], label=1.0),
<<<<<<< HEAD
   
=======
>>>>>>> 40ff4328ae445ee00a1c42d8d2b767dc5383daa6

    # 10. Events and Activities
    InputExample(texts=["What kind of extracurricular activities are available?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Is there a cultural festival?", "Are sports facilities available for students?"], label=1.0),
    InputExample(texts=["Do you have student clubs or societies?", "Are there opportunities for community service?"], label=1.0),
    InputExample(texts=["Does the college celebrate national holidays?", "Are there leadership development programs?"], label=1.0),

    # 11. Research Opportunities
    InputExample(texts=["Does the college support research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I participate in research projects?", "Is there funding available for research?"], label=1.0),
    InputExample(texts=["Are research internships offered?", "Do faculty members collaborate with students on research?"], label=1.0),
    InputExample(texts=["Does the college publish a research journal?", "Is there a research center for PhD students?"], label=1.0),
    InputExample(texts=["What types of research are being pursued in your lab?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Could you tell me about the main focus of your lab’s research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What research projects is your lab currently working on?", "Are there any research labs ava  ilable?"], label=1.0),
    InputExample(texts=["What areas of study does your lab specialize in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can you describe the research themes your lab focuses on?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What is the primary research goal in your lab?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What kind of scientific or academic work does your lab engage in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What are the main research topics explored in your lab?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Could you share some examples of research being conducted at your lab?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What are the key research interests of your team?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any labs that specialize in the area I am interested in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do you know of any research labs that focus on this topic?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any labs researching the subject I'm passionate about?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can you point me to any labs that focus on this area of research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there labs that have ongoing studies in the field I'm interested in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any teams currently researching topics like mine?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do you have any recommendations for labs working in this area?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is there a lab that is focusing on research similar to what I am interested in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any labs dedicated to this kind of research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can students showcase their research results at any events?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there platforms for students to share their research findings publicly?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Which labs are working on projects related to my field of interest?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do students have the chance to present their research to faculty or peers?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is there an opportunity for students to give presentations on their research work?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I present my research at any college-hosted conferences or symposia?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there opportunities for undergraduates to present their research outside of class?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any avenues for students to present their research to potential employers or researchers?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What is the best way to find a faculty mentor for my research project?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How can I approach a professor for research mentorship?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is there a formal process for connecting with a faculty member for research mentorship?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How can I find a professor who specializes in the area of research I am interested in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any resources to help me find a faculty mentor for research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is it possible for students to get their research papers published in academic journals?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do students have the opportunity to submit research papers to journals for publication?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any opportunities for students to publish their research in journals during their studies?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Am I allowed to do independent research in the lab on my own?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I carry out research in the lab without being part of a faculty-led project?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is it possible to conduct my own research in the lab without a professor's supervision?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What research facilities does this university offer?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can you tell me about the research labs on campus?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any research departments or labs at this university?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What kind of research opportunities are available in the labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any specialized research labs at this institution?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Could you provide information on the research labs available for students?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Does the university offer any financial support for student research projects?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can students apply for funding to support their research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any research-specific funding programs for students?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What funding options are available for students conducting research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How can students secure financial assistance for their research work?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is there financial aid available for students working in research labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any opportunities to receive funding for research-related expenses?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can student researchers receive any financial backing for their projects?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What kind of equipment do the research labs have?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can you tell me about the resources available in the labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What tools and equipment are provided for student researchers?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there specific research resources available for students to use?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What facilities and equipment can students access in the labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is there specialized lab equipment available for research purposes?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What types of instruments and resources are provided in the labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any advanced tools or technology in the research labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What resources do the research labs offer to support student projects?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is there any chance to collaborate with other universities or research centers?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are students encouraged to partner with external research institutions?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Does the university offer opportunities for joint research with other schools?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any collaborative research programs with other universities?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can students participate in research projects with other institutions?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any cross-university or institutional research partnerships available?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Does this university facilitate research collaborations with external organizations?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["is there a network for working with researchers at other universities?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there opportunities for inter-institutional collaboration on research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How do I find research opportunities related to my major?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I collaborate with researchers from other universities or research labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How can I discover research projects that align with my major?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What is the best way to find research opportunities within my field of study?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Where can I look for research opportunities related to my major?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How do I get involved in research that is relevant to my area of study?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there specific programs or resources for finding research opportunities in my field?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How can I connect with faculty or labs working on topics related to my major?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can you guide me on how to find research positions in my discipline?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there research projects that are tailored to students in my major?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Where can I find research positions or projects that align with my career goals in my field?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any training sessions available for students working in research labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do students have access to workshops that help them prepare for lab work?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any educational programs or workshops to support students in the research labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What research topics are being explored in the labs right now?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any exciting research projects happening in the labs at the moment?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Could you share some of the projects being worked on in the labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any specific research projects I can get involved in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What types of research are faculty and students collaborating on in the labs?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can students present their research at conferences through the lab?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do students get the chance to present their findings at research conferences?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I present my research at a conference as part of a lab project?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Does the lab offer opportunities to present research at external or university-sponsored conferences?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I submit my research from the lab to academic conferences?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How can I get involved in presenting my research at conferences?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any student research opportunities available this semester?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any research positions for students in the upcoming semester?", "Are there any research labs available?"], label=1.0),


    # 12. International Collaboration
    InputExample(texts=["Does the college have international partnerships?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are there opportunities to study abroad?", "Does the college offer global exposure?"], label=1.0),
    InputExample(texts=["Are foreign language courses available?", "Does the college have collaboration with global universities?"], label=1.0),
    InputExample(texts=["Are international internships facilitated?", "What are the options for cross-cultural learning?"], label=1.0),

    # 13. Online Learning and Resources
    InputExample(texts=["Are online courses available?", "Can students access digital libraries?"], label=1.0),
    InputExample(texts=["What e-learning tools are provided?", "Does the college use online learning platforms?"], label=1.0),
    InputExample(texts=["Is there access to virtual labs?", "Are recorded lectures provided?"], label=1.0),
<<<<<<< HEAD
    InputExample(texts=["Are students taught using online simulations?", "Do you offer online certification programs?"], label=1.0)

]
=======
    InputExample(texts=["Are students taught using online simulations?", "Do you offer online certification programs?"], label=1.0),

    # 14, Exams
    InputExample(texts=["How can I download the exam timetable?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the schedule for semester exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are mid-term exams conducted at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the passing criteria for exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How are practical exams conducted at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I appear for exams if my attendance is below the required percentage?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the format of exams at BFGI (online/offline)?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the process to apply for re-examinations?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are there any open-book exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What happens if I miss an exam due to illness?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Does BFGI provide study material for exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are mock exams conducted at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I get previous years question papers at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are there any preparation workshops for exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I clarify doubts with faculty before exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Where can I collect the exam form at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I modify the details on my submitted exam form?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["When will admit cards be issued for exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I download my admit card?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What should I do if theres an error on my admit card?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is it mandatory to carry the admit card for exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I get a duplicate admit card if I lose the original?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["When are practical exams conducted at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the weightage of practical exams in the final grade?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How are practical exams evaluated at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are there specific dress codes for lab exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How should I prepare for viva-voce exams? ", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["When will the results be declared for exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I check my exam results online?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What should I do if my results are withheld?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How is the grading system structured at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I request a detailed marksheet after the results are announced?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I apply for re-evaluation of my exam papers?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the fee for re-evaluation at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["When will the re-evaluation results be declared?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the process for re-examination at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I reappear for an exam to improve my marks?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What are the reporting timings for exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are electronic devices allowed in the exam hall?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What documents are required to enter the exam hall?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I bring a water bottle to the exam hall?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What happens if I am late for an exam?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are there special provisions for students with disabilities during exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I get extra time for exams due to medical reasons?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I request a scribe for the exam?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are there separate exam arrangements for international students?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Does BFGI offer flexibility in exam schedules for emergencies?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What qualifies as an emergency to request an exam reschedule?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I apply for a flexible exam schedule?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is exam flexibility offered for personal emergencies?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Does BFGI provide alternative exam dates for missed exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the process for requesting an exam reschedule?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are exam rescheduling requests subject to approval?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How much notice is required to request a flexible exam schedule? ", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I reschedule exams due to sudden illness?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is a doctor’s certificate required for medical emergencies?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What happens if I fall sick on the day of the exam?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can exams be postponed for hospitalization?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Does BFGI offer separate exams for students recovering from major illnesses?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=[" Are mental health issues considered valid for exam flexibility?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How do I submit medical documents for rescheduling?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can exams be rescheduled for students undergoing surgery?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can exams be rescheduled due to family emergencies?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the policy for bereavement-related exam flexibility?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=[" Are weddings considered valid reasons for rescheduling exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can exams be postponed for religious obligations?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Does BFGI offer flexibility for students facing legal issues?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I request an extension due to unforeseen accidents?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are family crises considered valid reasons for rescheduling?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is flexibility offered for students managing childcare emergencies?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I request flexibility through the online portal?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is there a specific form for exam rescheduling at BFGI?" , "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=[" What supporting documents are required for a reschedule request?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How long does it take to get approval for a rescheduling request?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is a written application mandatory for requesting flexibility?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the deadline for submitting a rescheduling request?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I appeal if my flexibility request is denied?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Who decides if an exam rescheduling request is approved?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How soon are rescheduled exams conducted?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Will the rescheduled exam be of the same difficulty level?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are rescheduled exams held on weekends?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is there a separate venue for rescheduled exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are flexible exam schedules announced publicly or privately?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can rescheduled exams be taken online?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is the format of the rescheduled exam the same as the original?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are there additional fees for rescheduled exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Will rescheduled exams affect my overall grade calculation?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can exams be postponed during a declared emergency in the region?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are exams automatically rescheduled during curfews?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How does BFGI manage exams during extreme weather conditions?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can exams be deferred for students affected by transportation strikes?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can working students request a custom exam schedule?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is there exam flexibility for international students dealing with visa issues?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What happens if I miss a rescheduled exam?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are there penalties for frequently rescheduling exams? ", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I choose the date for my rescheduled exam?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How will I be notified of my rescheduled exam date?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can rescheduled exams be further postponed in case of emergencies?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Will my rescheduled exam clash with other classes or tests?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How is the integrity of rescheduled exams maintained?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are rescheduled exams recorded differently in the academic transcript? ", "What is the schedule for semester exams at BFGI?"], label=1.0)


] 

  


def get_training_data():
    """Return the training examples."""
    return train_examples

if __name__ == "__main__":
    print("This module contains intent training data for fine-tuning.")

>>>>>>> 40ff4328ae445ee00a1c42d8d2b767dc5383daa6
